---
abstract: 'Find a minimum required version of perl for Perl code'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  File::Spec: 0.80
  Test::More: 0.47
  Test::Script: 1.02
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Perl::MinimumVersion
name: Perl-MinimumVersion
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  File::Find::Rule: 0
  List::Util: 1.19
  PPI: 1.118
  Params::Util: 0.25
  perl: 5.005
  version: 0.76
resources:
  license: http://dev.perl.org/licenses/
version: 1.18
