name: Perl-MinimumVersion
version: 0.10
abstract: Find the minimum required Perl version for any code
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.80
requires:
  perl: 5.005
  version: 0.48
  Carp: 0
  List::Util: 1.15
  Params::Util: 0.06
  PPI: 1.103
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.370
