
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.620
distribution_type: module
version: 0.13
name: Perl-MinimumVersion
author: Adam Kennedy <cpan@ali.as>
license: perl
build_requires: 
  Test::More: 0.47
  File::Spec: 0.80
requires: 
  PPI: 1.109
  File::Find::Rule: 0
  List::Util: 1.17
  perl: 5.005
  Params::Util: 0.06
  version: 0.59
  Carp: 0
abstract: Find a minimum required version of perl for Perl code
